POST http://localhost:3001/api/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldyBVc2VyIiwiaWQiOiI2OTRmYzlkOWJiMmU2NzgxODViZmNlZGYiLCJpYXQiOjE3NjY4MzY3NDMsImV4cCI6MTc2Njg0MDM0M30.FaVxAdgex_RvxIR0MfD_Ro0RCFsoLihEKcNToirVrQ0
content-type: application/json

    {
        "content": "Note created test",
        "important": true
    }

