POST http://localhost:3001/api/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNoYW9saW4iLCJpZCI6IjY5MzU1NmEyYjQxMDZiNWY1NzBmYmNlYyIsImlhdCI6MTc2NTM4MTYyMywiZXhwIjoxNzY1Mzg1MjIzfQ.MQN_7kg8l89y1c2MLgtb-Z3udRGPfRsxWZAreZVYffk
content-type: application/json

    {
        "content": "Note created with no id from the request",
        "important": true
    }

