GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
    "title": "New meta AI",
    "author": "Clare",
    "url": "www/google.com/asdf/asdfasdf/asdf",
    "likes": 94
}

###
PUT http://localhost:3001/api/blogs/68d2b059425faa5ae325586f
content-type: application/json

{
    "title": "Youtube Ai",
    "author": "Maria",
    "url": "www/youtube.com/asdf/fasdf/asdf",
    "likes": 124
}

###
DELETE http://localhost:3001/api/blogs/68cd92ead86207cd61f078c9

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "jek",
    "name": "Renilto",
    "password": "her"
}

###
GET http://localhost:3001/api/users/

