GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldyBVc2VyIiwiaWQiOiI2OTM5MDAyZjIxNWYwZTk3NGJmOTNjMjQiLCJpYXQiOjE3NjUzODMwMjV9.VZJMwW9YER7TvZNa1C6vov4Ms-Df-NQv8H5zN1449dE

{
    "title": "Vem, que vem, que vem, com o pai",
    "author": "Clare",
    "url": "www/asdf",
    "likes": 1000
}

###
PUT http://localhost:3001/api/blogs/68d2b059425faa5ae325586f
content-type: application/json

{
    "title": "Youtube Ai",
    "author": "Maria",
    "url": "www/youtube.com/asdf/fasdf/asdf",
    "likes": 124
}

###
DELETE http://localhost:3001/api/blogs/69390252e19e6648c2368c71

-----------------------------------------------------------------------------------

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "new User",
    "name": "Renilto",
    "password": "her"
}

###
DELETE http://localhost:3001/api/users/6938f452b540731c7a987993

-----------------------------------------------------------------------------------
###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
      "username": "new User",
    "name": "Renilto",
    "password": "her"
}