GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/2

###
POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldyBVc2VyIiwiaWQiOiI2OTNhNmY0MWNjZjU0MzYwNDkzYmNiYzIiLCJpYXQiOjE3NjU0MzcyNjB9.7F_87MVgEbykh3dXjF2O2UVffdTgU33WDmuXCNy6LZU

{
    "title": "teste, teste, teste",
    "author": "Clare",
    "url": "www/asdf",
    "likes": 1000
}

###
PUT http://localhost:3001/api/blogs/68d2b059425faa5ae325586f
content-type: application/json

{
    "title": "Youtube Ai",
    "author": "Maria",
    "url": "www/youtube.com/asdf/fasdf/asdf",
    "likes": 124
}

###
DELETE http://localhost:3001/api/blogs/693a789504452c977883c380
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldyBVc2VyIiwiaWQiOiI2OTNhNmY0MWNjZjU0MzYwNDkzYmNiYzIiLCJpYXQiOjE3NjU0MzcyNjB9.7F_87MVgEbykh3dXjF2O2UVffdTgU33WDmuXCNy6LZU

-----------------------------------------------------------------------------------

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "new User",
    "name": "Renilto",
    "password": "123"
}

###
DELETE http://localhost:3001/api/users/6938f452b540731c7a987993

-----------------------------------------------------------------------------------
###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
      "username": "new User",
    "name": "Renilto",
    "password": "123"
}